codes_mapping = {
'Diagnosis_I01': '01',
'Diagnosis_I05': '02',
'Diagnosis_I06': '03',
'Diagnosis_I07': '04',
'Diagnosis_I08': '05',
'Diagnosis_I10': '06',
'Diagnosis_I11': '07',
'Diagnosis_I15': '08',
'Diagnosis_I16': '09',
'Diagnosis_I20.0': '10',
'Diagnosis_I20.1': '11',
'Diagnosis_I20.9': '12',
'Diagnosis_I21.0': '13',
'Diagnosis_I21.1': '14',
'Diagnosis_I21.21': '15',
'Diagnosis_I21.4': '16',
'Diagnosis_I22': '17',
'Diagnosis_I23': '18',
'Diagnosis_I25': '19',
'Diagnosis_I26': '20',
'Diagnosis_I30': '21',
'Diagnosis_I31': '22',
'Diagnosis_I33': '23',
'Diagnosis_I34': '24',
'Diagnosis_I35': '25',
'Diagnosis_I36': '26',
'Diagnosis_I37': '27',
'Diagnosis_I38': '28',
'Diagnosis_I40': '29',
'Diagnosis_I42': '30',
'Diagnosis_I44.2': '31',
'Diagnosis_I46': '32',
'Diagnosis_I47': '33',
'Diagnosis_I47.2': '34',
'Diagnosis_I48.9': '35',
'Diagnosis_I50': '36',
'Diagnosis_I71': '37',
'Diagnosis_I74': '38',
'Diagnosis_I80': '39',
'Diagnosis_R55': '40',
'Diagnosis_C38': '41',
'Diagnosis_D15.1': '42',
}

title_to_new_codes_mapping = {
'Rheumatic fever with heart involvement': '01',
'Rheumatic mitral valve diseases': '02',
'Rheumatic aortic valve diseases': '03',
'Rheumatic tricuspid valve diseases': '04',
'Multiple valve diseases': '05',
'Essential (primary) hypertension': '06',
'Hypertensive heart disease': '07',
'Secondary hypertension': '08',
'Hypertensive crisis': '09',
'Unstable angina': '10',
'Angina pectoris with documented spasm': '11',
'Angina pectoris, unspecified': '12',
'STEMI of anterior wall': '13',
'STEMI of inferior wall': '14',
'STEMI involving left circumflex coronary artery': '15',
'Non-ST elevation MI': '16',
'Subsequent STEMI and NSTEMI in 28 days': '17',
'Certain current complications following STEMI and NSTEMI (within the 28 day period)': '18',
'Chronic ischemic heart disease': '19',
'Pulmonary embolism': '20',
'Acute pericarditis': '21',
'Other diseases of pericardium': '22',
'Acute and subacute endocarditis': '23',
'Nonrheumatic mitral valve disorders': '24',
'Nonrheumatic aortic valve disorders': '25',
'Nonrheumatic tricuspid valve disorders': '26',
'Nonrheumatic pulmonary valve disorders': '27',
'Endocarditis, valve unspecified': '28',
'Acute myocarditis': '29',
'Cardiomyopathy': '30',
'Complete heart block': '31',
'Cardiac arrest': '32',
'Paroxysmal tachycardia': '33',
'Ventricular tachycardia': '34',
'Atrial fibrillation and atrial flutter, unspecified': '35',
'Heart failure': '36',
'Aortic aneurysm and dissection': '37',
'Arterial embolism and thrombosis': '38',
'Phlebitis and thrombophlebitis': '39',
'Syncope and collapse': '40',
'Malignant neoplasm of heart, mediastinum and pleura': '41',
'Myxoma  (Benign neoplasm of heart)': '42',
}